%YAML:1.0

#Debug
verbose: 1
eps: 0.000001

# pyramid parameters
pyr_num: 3
pyr_factor: 2

# feature parameters
grid_cell: 10
ftr_num: 500
image_width: 640
image_height: 480

# instrinsc
instrinsc:
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  d0: 0.2624
  d1: -0.9531
  d2: -0.0054
  d3: 0.0026
  d4: 1.1633

# some threshold
min_proj_error: 2.0
min_corner_thr: 200
min_track_thr: 50
min_inlier_thr: 50
min_disparty_thr: 10

# map parameter
key_frame_size: 8

# feature align
align_iter_cnt: 5

# pose optimize
pose_optimize_iter_cnt: 10
pose_optimize_inlier_thr: 20

# struct optimize
struct_optimize_iter_cnt: 10
struct_optimize_point_cnt: 100

# key frame select
track_exmin_feature_thr: 25
track_min_feature_thr: 50
track_move_distance: 1.5

# depth filter
depth_filter_track_max_gap: 3
depth_filter_iter_cnt: 8
